apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app-deploy
  labels:
    name: redis-app-deploy
    app: demo-voting-app
spec:
  replicas: 1
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: demo-voting-app
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
  selector:
    matchLabels:
      name: redis-pod
      app: demo-voting-app

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: demo-voting-app
spec:
  type: ClusterIP
  selector:
    name: redis-pod
    app: demo-voting-app
  ports:
    - port: 6379
      targetPort: 6379